name: PowerShell Execution & Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      # Inputs configuration remains the same
      deploymentMode:
        description: 'Select the deployment mode'
        required: true
        type: choice
        options:
          - BPT
          - NO_BPT
      customerType:
        description: 'Select the Customer Type'
        required: true
        type: choice
        options:
          - CLOUD_ESSENTIALS
          - CLOUD_BP_CONFIG
          - CLOUD
      subscriptionName:
        description: 'Enter the subscription name'
        required: true
        type: choice
        options:
          - BMQR-BPT-DEVELOPMENT
          - BMQR-BPT-PRODUCTION
          - OTHER
      resourceGroup:
        description: 'Enter the resource group'
        required: true
        type: choice
        options:
          - dev-r4-dev-cei-eus-rg-01
          - BMQR_IT
          - BMQR
      clusterName:
        description: 'Enter the cluster name'
        required: true
        type: choice
        options:
          - olympus
          - sinai
          - elbrus
        default: sinai
      bmqrAdminUser:
        description: 'Enter the BMQR Admin User'
        required: true
        type: string
        default: Rdoddi@coolblue.com
      bmqrPMUser:
        description: 'Enter the BMQR PM User'
        required: true
        type: string
        default: aehileman@coolblue.com
        
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Git LFS
      run: git lfs install
      shell: pwsh
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Verify LFS Files
      run: |
        echo "Verifying LFS files:"
        git lfs ls-files
        git lfs pull
      shell: pwsh

    - name: Ensure All LFS Files are Fetched
      run: |
        echo "Fetching all LFS files:"
        git lfs fetch --all
        git lfs checkout
      shell: pwsh

    - name: List File Sizes in Repository
      run: |
        echo "Listing files with sizes in KB:"
        Get-ChildItem -Recurse | Select-Object Name, @{Name="SizeKB";Expression={[math]::round($_.Length / 1KB, 2)}} | Format-Table -AutoSize
      shell: pwsh

    - name: Verify Specific LFS File
      run: |
        echo "Verifying specific LFS file sizes:"
        git lfs ls-files -l
        git lfs status
        Get-ChildItem -Recurse -File | Where-Object { $_.Name -match '<specific-file-name>' } | Format-List Name, Length
      shell: pwsh
