name: PowerShell Execution & Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      # Inputs configuration remains the same
      deploymentMode:
        description: 'Select the deployment mode'
        required: true
        type: choice
        options:
          - BPT
          - NO_BPT
      customerType:
        description: 'Select the Customer Type'
        required: true
        type: choice
        options:
          - CLOUD_ESSENTIALS
          - CLOUD_BP_CONFIG
          - CLOUD
      subscriptionName:
        description: 'Enter the subscription name'
        required: true
        type: choice
        options:
          - BMQR-BPT-DEVELOPMENT
          - BMQR-BPT-PRODUCTION
          - OTHER
      resourceGroup:
        description: 'Enter the resource group'
        required: true
        type: choice
        options:
          - dev-r4-dev-cei-eus-rg-01
          - BMQR_IT
          - BMQR
      clusterName:
        description: 'Enter the cluster name'
        required: true
        type: choice
        options:
          - olympus
          - sinai
          - elbrus
        default: sinai
      bmqrAdminUser:
        description: 'Enter the BMQR Admin User'
        required: true
        type: string
        default: Rdoddi@coolblue.com
      bmqrPMUser:
        description: 'Enter the BMQR PM User'
        required: true
        type: string
        default: aehileman@coolblue.com
        
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository with LFS
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      # Step 2: Verify Git LFS installation
      - name: Verify Git LFS Installation
        run: git lfs install

      - name: Pull LFS Files
        run: git lfs pull

      # Step 3: Show file sizes in MB
      - name: Display File Sizes in MB
        shell: pwsh
        run: |
          Write-Host "Displaying file sizes in MB:"
          Get-ChildItem -Path . -Recurse | 
          Where-Object { -not $_.PSIsContainer } | 
          Select-Object Name, @{Name='Size(MB)'; Expression={[math]::Round($_.Length / 1MB, 2)}} | 
          Format-Table -AutoSize
        