on: [push]

name: InstallAzureCLI

jobs:
  install-and-configure:
    runs-on: windows-latest  # Specifies a self-hosted Windows runner
    steps:
      - name: Install Azure CLI using PowerShell
        run: |
          Write-Host "Downloading and installing Azure CLI..."
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
        shell: pwsh  # Ensure PowerShell is used as the shell

      - name: Verify Azure CLI Installation
        run: az --version